
# map: true
# module: false
plugins:
  postcss-fontpath:
    checkFiles: true
    ie8Fix: true
  tailwindcss: "./tailwind.config.js"
  postcss-font-magician:
    hosted: ["./fonts"]
  autoprefixer: true


# purge-css
