name: publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  push-subtree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Git
        run: |
          git config --local user.email "hey@mattforster.ca"
          git config --local user.name "Matt Forster"
      - name: Build & Publish
        run: npm run push
