name: publish

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  push-subtree:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Git
        run: |
          git config --local user.email "hey@mattforster.ca"
          git config --local user.name "Matt Forster"

      # Runs a set of commands using the runners shell
      - name: Build & Publish
        run: npm run push
