name: publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  push-subtree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: yarn install --frozen-lockfile
      - run: git config --local user.email "bot@mattforster.ca"
      - run: yarn push
